"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 15:07:46.936445
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('dedup_key', sa.String(length=300), nullable=False),
    sa.Column('complex_no', sa.String(length=32), nullable=False),
    sa.Column('area_key', sa.Float(), nullable=False),
    sa.Column('first_alerted_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_alerted_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_alerted_price', sa.Integer(), nullable=False),
    sa.Column('last_seen_run_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_run_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('dedup_key', name=op.f('pk_alert_history'))
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_history_complex_no'), ['complex_no'], unique=False)

    op.create_table('complexes',
    sa.Column('complex_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lawd_cd', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('max_floor', sa.Integer(), nullable=True),
    sa.Column('molit_apt_seq', sa.String(length=64), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('complex_no', name=op.f('pk_complexes'))
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('cross_check_warnings', sa.JSON(), nullable=False),
    sa.Column('complex_results', sa.JSON(), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_started_at'), ['started_at'], unique=False)

    op.create_table('area_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complex_no', sa.String(length=32), nullable=False),
    sa.Column('area_key', sa.Float(), nullable=False),
    sa.Column('exclusive_m2', sa.Float(), nullable=False),
    sa.Column('supply_m2', sa.Float(), nullable=False),
    sa.Column('pyeong', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complex_no'], ['complexes.complex_no'], name=op.f('fk_area_types_complex_no_complexes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area_types')),
    sa.UniqueConstraint('complex_no', 'area_key', name='uq_area_types_complex_area')
    )
    op.create_table('listings_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('article_no', sa.String(length=32), nullable=False),
    sa.Column('complex_no', sa.String(length=32), nullable=False),
    sa.Column('area_key', sa.Float(), nullable=False),
    sa.Column('dong', sa.String(length=50), nullable=False),
    sa.Column('floor_raw', sa.String(length=50), nullable=False),
    sa.Column('floor_group', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.Date(), nullable=True),
    sa.Column('realtor_count', sa.Integer(), nullable=False),
    sa.Column('alt_prices', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_listings_snapshot_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings_snapshot')),
    sa.UniqueConstraint('run_id', 'dedup_key', name='uq_listings_snapshot_run_dedup')
    )
    with op.batch_alter_table('listings_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_listings_snapshot_complex_area', ['complex_no', 'area_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_snapshot_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_snapshot_run_id'), ['run_id'], unique=False)

    op.create_table('trades_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('complex_no', sa.String(length=32), nullable=False),
    sa.Column('area_key', sa.Float(), nullable=False),
    sa.Column('exclusive_m2', sa.Float(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('floor_group', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('deal_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_trades_snapshot_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades_snapshot'))
    )
    with op.batch_alter_table('trades_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_trades_snapshot_complex_area', ['complex_no', 'area_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_snapshot_run_id'), ['run_id'], unique=False)

    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('listing_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sa.String(length=300), nullable=False),
    sa.Column('is_bargain', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('trade_base', sa.Integer(), nullable=True),
    sa.Column('listing_base', sa.Integer(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('trade_sample_short', sa.Boolean(), nullable=False),
    sa.Column('alert_kind', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['listing_snapshot_id'], ['listings_snapshot.id'], name=op.f('fk_verdicts_listing_snapshot_id_listings_snapshot'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_verdicts_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verdicts')),
    sa.UniqueConstraint('listing_snapshot_id', name=op.f('uq_verdicts_listing_snapshot_id'))
    )
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verdicts_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verdicts_run_id'))
        batch_op.drop_index(batch_op.f('ix_verdicts_dedup_key'))

    op.drop_table('verdicts')
    with op.batch_alter_table('trades_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_snapshot_run_id'))
        batch_op.drop_index('ix_trades_snapshot_complex_area')

    op.drop_table('trades_snapshot')
    with op.batch_alter_table('listings_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_snapshot_run_id'))
        batch_op.drop_index(batch_op.f('ix_listings_snapshot_dedup_key'))
        batch_op.drop_index('ix_listings_snapshot_complex_area')

    op.drop_table('listings_snapshot')
    op.drop_table('area_types')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_started_at'))

    op.drop_table('runs')
    op.drop_table('complexes')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_history_complex_no'))

    op.drop_table('alert_history')
    # ### end Alembic commands ###
